name: My First Workflow
on:
  push:
    branches:
      - main

jobs:
  hello_job:
    runs-on: ubunto-lasted
    steps:

      - name: Simple greeting
        run: echo "Hello, GitHub Actions!"
      - name: Show current date
        run: date
      - name : List current directory
        run: ls -la
  check_system:
    runs-on: unbunto-lasted
    steps:
      - name: Show system information
        run: |
          echo "=== System Info ==="
          echo "Operating System: $(uname -s)"
          echo "Current User: $(whoami)"
          echo "Working Directory: $(pwd)"
      - name: Create a simple file
        run: |
          echo "This is a test file" > test.txt
          cat test.txt
  Summary_Report:
    runs-on: unbunto-lasted
    steps:
      - name: Wait message
        run: echo "Both previous jobs completed successfully!"
      - name: Final summary
        run: |
          echo "=== Workflow Summary ==="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "All jobs completed at: $(date)"